name: Cypress Simple Factorial
on: [push] 
jobs:
  cypress-run:
    runs-on: ubuntu-ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
