name: Cypress Simple Factorial
on: [push] 
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cypress.io
        uses: cypress-io/github-action@v6
        with:
          start: npm run test
          record: true
          publish-summary: true
          component: true